/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as PoliticaEditorialRouteImport } from './routes/politica-editorial'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UltimasRouteImport } from './routes/ultimas'
import { Route as CategoriaIndexRouteImport } from './routes/$categoria.index'
import { Route as CategoriaSlugRouteImport } from './routes/$categoria.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AdminAudienciaRouteImport } from './routes/admin.audiencia'
import { Route as AdminFeedsRouteImport } from './routes/admin.feeds'
import { Route as AdminGenerateRouteImport } from './routes/admin.generate'
import { Route as AdminGradeRouteImport } from './routes/admin.grade'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminTopicsRouteImport } from './routes/admin.topics'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaEditorialRoute = PoliticaEditorialRouteImport.update({
  id: '/politica-editorial',
  path: '/politica-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UltimasRoute = UltimasRouteImport.update({
  id: '/ultimas',
  path: '/ultimas',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaIndexRoute = CategoriaIndexRouteImport.update({
  id: '/$categoria/',
  path: '/$categoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/$categoria/$slug',
  path: '/$categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAudienciaRoute = AdminAudienciaRouteImport.update({
  id: '/audiencia',
  path: '/audiencia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedsRoute = AdminFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerateRoute = AdminGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGradeRoute = AdminGradeRouteImport.update({
  id: '/grade',
  path: '/grade',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopicsRoute = AdminTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/ao-vivo': typeof AoVivoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultimas': typeof UltimasRoute
  '/$categoria/$slug': typeof CategoriaSlugRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/audiencia': typeof AdminAudienciaRoute
  '/admin/feeds': typeof AdminFeedsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/grade': typeof AdminGradeRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin/login': typeof AdminLoginRoute
  '/post/$slug': typeof PostSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/$categoria/': typeof CategoriaIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/anuncie': typeof AnuncieRoute
  '/ao-vivo': typeof AoVivoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultimas': typeof UltimasRoute
  '/$categoria/$slug': typeof CategoriaSlugRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/audiencia': typeof AdminAudienciaRoute
  '/admin/feeds': typeof AdminFeedsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/grade': typeof AdminGradeRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin/login': typeof AdminLoginRoute
  '/post/$slug': typeof PostSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/$categoria': typeof CategoriaIndexRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/ao-vivo': typeof AoVivoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultimas': typeof UltimasRoute
  '/$categoria/$slug': typeof CategoriaSlugRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/audiencia': typeof AdminAudienciaRoute
  '/admin/feeds': typeof AdminFeedsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/grade': typeof AdminGradeRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/post/$slug': typeof PostSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/$categoria/': typeof CategoriaIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/anuncie'
    | '/ao-vivo'
    | '/feed.xml'
    | '/mcp'
    | '/pending-approval'
    | '/politica-editorial'
    | '/sitemap.xml'
    | '/ultimas'
    | '/$categoria/$slug'
    | '/.well-known/oauth-protected-resource'
    | '/admin/$'
    | '/admin/audiencia'
    | '/admin/feeds'
    | '/admin/generate'
    | '/admin/grade'
    | '/admin/help'
    | '/admin/integrations'
    | '/admin/logs'
    | '/admin/news'
    | '/admin/onboarding'
    | '/admin/posts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/topics'
    | '/admin/login'
    | '/post/$slug'
    | '/tag/$slug'
    | '/$categoria/'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/admin/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/anuncie'
    | '/ao-vivo'
    | '/feed.xml'
    | '/mcp'
    | '/pending-approval'
    | '/politica-editorial'
    | '/sitemap.xml'
    | '/ultimas'
    | '/$categoria/$slug'
    | '/.well-known/oauth-protected-resource'
    | '/admin/$'
    | '/admin/audiencia'
    | '/admin/feeds'
    | '/admin/generate'
    | '/admin/grade'
    | '/admin/help'
    | '/admin/integrations'
    | '/admin/logs'
    | '/admin/news'
    | '/admin/onboarding'
    | '/admin/posts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/topics'
    | '/admin/login'
    | '/post/$slug'
    | '/tag/$slug'
    | '/$categoria'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/admin/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/anuncie'
    | '/ao-vivo'
    | '/feed.xml'
    | '/mcp'
    | '/pending-approval'
    | '/politica-editorial'
    | '/sitemap.xml'
    | '/ultimas'
    | '/$categoria/$slug'
    | '/.well-known/oauth-protected-resource'
    | '/admin/$'
    | '/admin/audiencia'
    | '/admin/feeds'
    | '/admin/generate'
    | '/admin/grade'
    | '/admin/help'
    | '/admin/integrations'
    | '/admin/logs'
    | '/admin/news'
    | '/admin/onboarding'
    | '/admin/posts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/topics'
    | '/admin_/login'
    | '/post/$slug'
    | '/tag/$slug'
    | '/$categoria/'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/admin/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnuncieRoute: typeof AnuncieRoute
  AoVivoRoute: typeof AoVivoRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  McpRoute: typeof McpRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  PoliticaEditorialRoute: typeof PoliticaEditorialRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UltimasRoute: typeof UltimasRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  PostSlugRoute: typeof PostSlugRoute
  TagSlugRoute: typeof TagSlugRoute
  CategoriaIndexRoute: typeof CategoriaIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-editorial': {
      id: '/politica-editorial'
      path: '/politica-editorial'
      fullPath: '/politica-editorial'
      preLoaderRoute: typeof PoliticaEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ultimas': {
      id: '/ultimas'
      path: '/ultimas'
      fullPath: '/ultimas'
      preLoaderRoute: typeof UltimasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categoria/': {
      id: '/$categoria/'
      path: '/$categoria'
      fullPath: '/$categoria/'
      preLoaderRoute: typeof CategoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categoria/$slug': {
      id: '/$categoria/$slug'
      path: '/$categoria/$slug'
      fullPath: '/$categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audiencia': {
      id: '/admin/audiencia'
      path: '/audiencia'
      fullPath: '/admin/audiencia'
      preLoaderRoute: typeof AdminAudienciaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feeds': {
      id: '/admin/feeds'
      path: '/feeds'
      fullPath: '/admin/feeds'
      preLoaderRoute: typeof AdminFeedsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generate': {
      id: '/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AdminGenerateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grade': {
      id: '/admin/grade'
      path: '/grade'
      fullPath: '/admin/grade'
      preLoaderRoute: typeof AdminGradeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/topics': {
      id: '/admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminTopicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
  }
}

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminAudienciaRoute: typeof AdminAudienciaRoute
  AdminFeedsRoute: typeof AdminFeedsRoute
  AdminGenerateRoute: typeof AdminGenerateRoute
  AdminGradeRoute: typeof AdminGradeRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTopicsRoute: typeof AdminTopicsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminAudienciaRoute: AdminAudienciaRoute,
  AdminFeedsRoute: AdminFeedsRoute,
  AdminGenerateRoute: AdminGenerateRoute,
  AdminGradeRoute: AdminGradeRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTopicsRoute: AdminTopicsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  AnuncieRoute: AnuncieRoute,
  AoVivoRoute: AoVivoRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  McpRoute: McpRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  PoliticaEditorialRoute: PoliticaEditorialRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UltimasRoute: UltimasRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminLoginRoute: AdminLoginRoute,
  PostSlugRoute: PostSlugRoute,
  TagSlugRoute: TagSlugRoute,
  CategoriaIndexRoute: CategoriaIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
